In [4]:
# TASK1

import numpy as np
v = np.arange(2, 33, 2).reshape(4, 4)
print(v)



[[ 2  4  6  8]
 [10 12 14 16]
 [18 20 22 24]
 [26 28 30 32]]


In [5]:
# TASK2

import numpy as np
original_array = np.arange(1, 26).reshape(5, 5)
odd_numbers_array = original_array[original_array % 2 != 0]

print("Original 5x5 array:")
print(original_array)

print("\nArray with only odd numbers:")
print(odd_numbers_array)


Original 5x5 array:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]

Array with only odd numbers:
[ 1  3  5  7  9 11 13 15 17 19 21 23 25]


In [6]:
# TASK3

import numpy as np
V = np.arange(1, 5).reshape(4, 1) * np.ones((1, 4), dtype=int)

print(V)


[[1 1 1 1]
 [2 2 2 2]
 [3 3 3 3]
 [4 4 4 4]]
